### ISSUE TITLE
Use lowercase status values

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-telesign#21]
Other integrations such as BriteVerify use lower case. It would be good to have these be lower case too, just for consistency. We have folks that are ready to make rules on these values, but we want to present character case that is uniform with other integrations.

https://github.com/activeprospect/leadconduit-integration-telesign/blob/101b9806008e5e7163e0a70d330daaa807c157b1/src/phone.coffee#L101-L102

**Comment by zalary** [comment]
resolved with PR #22

**Comment by alexkwolfe** [comment]
This didn't make it to production with the latest deploy.

**Comment by alexkwolfe** [comment]
The problem is [https://github.com/activeprospect/leadconduit-integrations/blob/master/package.json#L48](here). According to the [semver spec](https://github.com/npm/node-semver#tilde-ranges-123-12-1), `~0.4.0` will allow `>=0.4.0 <0.5.0`. Therefore, the current version of this module (`0.6.0`) is excluded.

I recommend bumping the version of this module to `1.0.0` and changing leadconduit-integrations to `^1.0.0`.

**Comment by ros3bud** [comment]
Double checked and this is working now.
